CREATE TABLE USERS (
		user_id bigint generated by default as identity,
        name varchar(255),
        role varchar(255),
        primary key (user_id)
        
        );
        
CREATE TABLE VALUE_RECORDS (
		value_id bigint generated by default as identity,
        data timestamp(6),
        descricao varchar(255),
        tipo boolean not null,
        user_id bigint,
        valor varchar(255),
        primary key (value_id)
        );
INSERT INTO USERS
VALUES (1, 'Eduardo Abreu', 'admin');


INSERT INTO VALUE_RECORDS
VALUES 
('1','05/01/22','Salário','true','1','8500')
('2','07/01/22','Cartão de crédito','false','1','1500')
('3','23/01/22','IPVA','false','1','2500')
('4','25/01/22','IPTU','false','1','1500')
('5','06/01/22','Faculdade','false','1','690')
('6','10/01/22','Conta de Celular','false','1','50')
('7','05/01/22','Financiamento Casa','false','1','1800');